PlanarGC: DijkHeap Class Reference
DijkHeap Class Reference
#include <CGraph.h>
Public Member Functions
DijkHeap (uint maxHeapSize)
~DijkHeap ()
HeapId insert (CDijkNode &node)
void decrease (HeapId node, CapType amount)
bool deleteMin (CDijkNode &node)
bool getMin (CDijkNode &node)
double getMin ()
bool isempty ()
HeapId deleteLast ()
void insert (HeapId node)
Constructor & Destructor Documentation
DijkHeap::DijkHeap (uint maxHeapSize)
DijkHeap::~DijkHeap ()
Member Function Documentation
HeapId DijkHeap::insert (CDijkNode & node)
References CDijkNode::heapId, and CDijkNode::heapNr.
Referenced by CGraph::runDijkstra().
void DijkHeap::decrease (HeapId node, CapType amount)
References CDijkNode::dijkWeight, and CDijkNode::heapId.
Referenced by CGraph::runDijkstra().
bool DijkHeap::deleteMin (CDijkNode & node)
References CDijkNode::heapId.
Referenced by CGraph::runDijkstra().
bool DijkHeap::getMin (CDijkNode & node)
double DijkHeap::getMin ()
References CDijkNode::dijkWeight.
bool DijkHeap::isempty ()
HeapId DijkHeap::deleteLast ()
void DijkHeap::insert (HeapId node)
References CDijkNode::heapId.
© 2009 - 2013 by Eno Töppe, Frank R. Schmidt
generated by Doxygen